version: '3.8'

services:
  db:
    image: postgres:latest
    restart: always
    ports:
      - "5431:5432"
    volumes:
      - db:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: "Wa20112016"
      POSTGRES_DB: "mobiauto" 

volumes:
  db:
    driver: local

#  docker-compose  --env-file .\.env up