spring:
  application:
    name: "mobiauto"
  datasource:
    url: "jdbc:postgresql://localhost:5431/mobiauto"
    username: "postgres"
    password: "Wa20112016"
    driverClassName: "org.postgresql.Driver"
  sql:
    init:
      mode: always
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        use_sql_comments: true
